#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: user-management
#          uri: http://localhost:8000
#          predicates:
#            - Path=/test/**
#          filters:
#            - name: GlobalPreFilter
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: TRACE